import { Component, OnInit } from '@angular/core';

@Component({
  selector: '', // Generated by app.routes.ts
  templateUrl: './app-welcome.component.html',
  styleUrls: ['./app-welcome.component.css']
})
export class AppWelcomeComponent implements OnInit {

  urlIT: string;
  urlAngular: string;
  urlCLI: string;
  urlMat: string;
  urlTs: string;
  urlECMA6: string;
  urlHTML5: string;
  urlCSS3: string;
  urlMaterialCSS: string;
  urlNode: string;

  constructor() {

  this.urlIT ="https://cibernarium.barcelonactiva.cat/it-academy?utm_source=Adwords&utm_medium=SEM&utm_campaign=IT%20Academy%202018";
  this.urlAngular="https://angular.io/";
  this.urlCLI="https://cli.angular.io/";
  this.urlMat="https://material.angular.io/";
  this.urlTs="https://www.typescriptlang.org/";
  this.urlECMA6="http://es6-features.org";
  this.urlHTML5="https://developer.mozilla.org/es/docs/HTML/HTML5";
  this.urlCSS3="https://developer.mozilla.org/es/docs/Web/CSS/CSS3";
  this.urlMaterialCSS="https://materializecss.com/";
  this.urlNode="https://nodejs.org/es/";
}

  ngOnInit() {
  }

}
