import { Component, OnInit } from '@angular/core';

@Component({
  selector: '',  // Generated by app.routes.ts
  templateUrl: './app-about.component.html',
  styleUrls: ['./app-about.component.css']
})
export class AppAboutComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
